use serde::{Deserialize};

#[derive(Debug, Deserialize)]
pub struct AnalyticsSettings  {
	#[serde(rename = "alwaysGenPreviews")]
	pub always_gen_previews: Option<bool>,
	#[serde(rename = "analyticsAdoptionMetadata")]
	pub analytics_adoption_metadata: Option<bool>,
	#[serde(rename = "autoInstallApps")]
	pub auto_install_apps: Option<bool>,
	#[serde(rename = "canAccessAnalyticsViaAPI")]
	pub can_access_analytics_via_api: Option<bool>,
	#[serde(rename = "canAnnotateDashboards")]
	pub can_annotate_dashboards: Option<bool>,
	#[serde(rename = "canEnableSavedView")]
	pub can_enable_saved_view: Option<bool>,
	#[serde(rename = "canExploreDataConversationally")]
	pub can_explore_data_conversationally: Option<bool>,
	#[serde(rename = "canShareAppsWithCommunities")]
	pub can_share_apps_with_communities: Option<bool>,
	#[serde(rename = "canViewThumbnailAssets")]
	pub can_view_thumbnail_assets: Option<bool>,
	#[serde(rename = "enableAmazonRedshiftOutputConnector")]
	pub enable_amazon_redshift_output_connector: Option<bool>,
	#[serde(rename = "enableAnalyticsEncryption")]
	pub enable_analytics_encryption: Option<bool>,
	#[serde(rename = "enableAnalyticsSharingEnable")]
	pub enable_analytics_sharing_enable: Option<bool>,
	#[serde(rename = "enableAutoCompleteCombo")]
	pub enable_auto_complete_combo: Option<bool>,
	#[serde(rename = "enableAutonomousExperience")]
	pub enable_autonomous_experience: Option<bool>,
	#[serde(rename = "enableAzureDLGen2OutputConnector")]
	pub enable_azure_dl_gen_2_output_connector: Option<bool>,
	#[serde(rename = "enableC360GlobalProfileData")]
	pub enable_c_360_global_profile_data: Option<bool>,
	#[serde(rename = "enableCreateLegacyDataflows")]
	pub enable_create_legacy_dataflows: Option<bool>,
	#[serde(rename = "enableDashboardComponentSnapshot")]
	pub enable_dashboard_component_snapshot: Option<bool>,
	#[serde(rename = "enableDashboardFlexiTable")]
	pub enable_dashboard_flexi_table: Option<bool>,
	#[serde(rename = "enableDashboardToPDFEnable")]
	pub enable_dashboard_to_pdf_enable: Option<bool>,
	#[serde(rename = "enableEmailReportsToPortalUsers")]
	pub enable_email_reports_to_portal_users: Option<bool>,
	#[serde(rename = "enableFirebirdEditor")]
	pub enable_firebird_editor: Option<bool>,
	#[serde(rename = "enableFloatingReportHeaders")]
	pub enable_floating_report_headers: Option<bool>,
	#[serde(rename = "enableInsights")]
	pub enable_insights: Option<bool>,
	#[serde(rename = "enableInsightsHCMode")]
	pub enable_insights_hc_mode: Option<bool>,
	#[serde(rename = "enableLightningReportBuilder")]
	pub enable_lightning_report_builder: Option<bool>,
	#[serde(rename = "enableLotusNotesImages")]
	pub enable_lotus_notes_images: Option<bool>,
	#[serde(rename = "enableMassEnableReportBuilder")]
	pub enable_mass_enable_report_builder: Option<bool>,
	#[serde(rename = "enableNewChartsEngine")]
	pub enable_new_charts_engine: Option<bool>,
	#[serde(rename = "enableNullDimension")]
	pub enable_null_dimension: Option<bool>,
	#[serde(rename = "enableOrgCanSeeLivePreviews")]
	pub enable_org_can_see_live_previews: Option<bool>,
	#[serde(rename = "enableOrgCanViewTableau")]
	pub enable_org_can_view_tableau: Option<bool>,
	#[serde(rename = "enableOrgCanViewThumbnailForOA")]
	pub enable_org_can_view_thumbnail_for_oa: Option<bool>,
	#[serde(rename = "enableOrgHasMobileOfflineEnabled")]
	pub enable_org_has_mobile_offline_enabled: Option<bool>,
	#[serde(rename = "enableOrgHasWatchlistEnabled")]
	pub enable_org_has_watchlist_enabled: Option<bool>,
	#[serde(rename = "enableQueryLiveConnectors")]
	pub enable_query_live_connectors: Option<bool>,
	#[serde(rename = "enableRemoveFooterForRepDisplay")]
	pub enable_remove_footer_for_rep_display: Option<bool>,
	#[serde(rename = "enableRemoveFooterFromRepExp")]
	pub enable_remove_footer_from_rep_exp: Option<bool>,
	#[serde(rename = "enableReportHideXlsExportPref")]
	pub enable_report_hide_xls_export_pref: Option<bool>,
	#[serde(rename = "enableReportInlineEditPref")]
	pub enable_report_inline_edit_pref: Option<bool>,
	#[serde(rename = "enableReportNotificationsEnable")]
	pub enable_report_notifications_enable: Option<bool>,
	#[serde(rename = "enableRequestPrioritySchdl")]
	pub enable_request_priority_schdl: Option<bool>,
	#[serde(rename = "enableS1AnalyticsEclairEnable")]
	pub enable_s_1_analytics_eclair_enable: Option<bool>,
	#[serde(rename = "enableS3OutputConnector")]
	pub enable_s_3_output_connector: Option<bool>,
	#[serde(rename = "enableSFXJoinedReportsEnable")]
	pub enable_sfx_joined_reports_enable: Option<bool>,
	#[serde(rename = "enableSalesforceOutputConnector")]
	pub enable_salesforce_output_connector: Option<bool>,
	#[serde(rename = "enableSecureImageSharing")]
	pub enable_secure_image_sharing: Option<bool>,
	#[serde(rename = "enableSnowflakeOutputConnector")]
	pub enable_snowflake_output_connector: Option<bool>,
	#[serde(rename = "enableTableauHyperOutputConnector")]
	pub enable_tableau_hyper_output_connector: Option<bool>,
	#[serde(rename = "enableUseOldChartsLookAndFeel")]
	pub enable_use_old_charts_look_and_feel: Option<bool>,
	#[serde(rename = "enableWaveAssetsNewDateVersion")]
	pub enable_wave_assets_new_date_version: Option<bool>,
	#[serde(rename = "enableWaveCustomFiscal")]
	pub enable_wave_custom_fiscal: Option<bool>,
	#[serde(rename = "enableWaveIndexMVDim")]
	pub enable_wave_index_mv_dim: Option<bool>,
	#[serde(rename = "enableWaveIndexMVDimV2")]
	pub enable_wave_index_mv_dim_v_2: Option<bool>,
	#[serde(rename = "enableWaveMultiCurrency")]
	pub enable_wave_multi_currency: Option<bool>,
	#[serde(rename = "enableWaveRecordNavigation")]
	pub enable_wave_record_navigation: Option<bool>,
	#[serde(rename = "enableWaveReplication")]
	pub enable_wave_replication: Option<bool>,
	#[serde(rename = "enableWaveSharingInheritance")]
	pub enable_wave_sharing_inheritance: Option<bool>,
	#[serde(rename = "enableWaveSqlCFIndexing")]
	pub enable_wave_sql_cf_indexing: Option<bool>,
	#[serde(rename = "enableWaveTrendedDatasetCleanup")]
	pub enable_wave_trended_dataset_cleanup: Option<bool>,
	#[serde(rename = "etlOrchestrationPref")]
	pub etl_orchestration_pref: Option<bool>,
	#[serde(rename = "isHighVolumePushbackEnabled")]
	pub is_high_volume_pushback_enabled: Option<bool>,
	#[serde(rename = "maxHoursAppInProgress")]
	pub max_hours_app_in_progress: Option<i32>,
	#[serde(rename = "recipeDirectDataPref")]
	pub recipe_direct_data_pref: Option<bool>,
	#[serde(rename = "recipeFiscalPref")]
	pub recipe_fiscal_pref: Option<bool>,
	#[serde(rename = "recipePreCachingOptOut")]
	pub recipe_pre_caching_opt_out: Option<bool>,
	#[serde(rename = "recipeStagedDataPref")]
	pub recipe_staged_data_pref: Option<bool>,
	#[serde(rename = "replaceBlankMeasuresWithNulls")]
	pub replace_blank_measures_with_nulls: Option<bool>,
	#[serde(rename = "setWaveIsYearEndFiscalYear")]
	pub set_wave_is_year_end_fiscal_year: Option<bool>,
	#[serde(rename = "sonicEnabled")]
	pub sonic_enabled: Option<bool>,
	#[serde(rename = "turnOnTimeZones")]
	pub turn_on_time_zones: Option<bool>,
	#[serde(rename = "fullName")]
	pub full_name: Option<String>,
}
