use crate::metadata::EmailToCaseSettings::EmailToCaseSettings;
use crate::metadata::FeedItemSettings::FeedItemSettings;
use crate::metadata::WebToCaseSettings::WebToCaseSettings;
use serde::{Deserialize};

#[derive(Debug, Deserialize)]
pub struct CaseSettings  {
	#[serde(rename = "caseAssignNotificationTemplate")]
	pub case_assign_notification_template: Option<String>,
	#[serde(rename = "caseAutoProcUser")]
	pub case_auto_proc_user: Option<bool>,
	#[serde(rename = "caseCloseNotificationTemplate")]
	pub case_close_notification_template: Option<String>,
	#[serde(rename = "caseCommentNotificationTemplate")]
	pub case_comment_notification_template: Option<String>,
	#[serde(rename = "caseCreateNotificationTemplate")]
	pub case_create_notification_template: Option<String>,
	#[serde(rename = "caseFeedItemSettings")]
	pub case_feed_item_settings: Option<Vec<FeedItemSettings>>,
	#[serde(rename = "caseFeedReadUnreadLtng")]
	pub case_feed_read_unread_ltng: Option<bool>,
	#[serde(rename = "caseMergeInLightning")]
	pub case_merge_in_lightning: Option<bool>,
	#[serde(rename = "closeCaseThroughStatusChange")]
	pub close_case_through_status_change: Option<bool>,
	#[serde(rename = "defaultCaseFeedLayoutOn")]
	pub default_case_feed_layout_on: Option<bool>,
	#[serde(rename = "defaultCaseOwner")]
	pub default_case_owner: Option<String>,
	#[serde(rename = "defaultCaseOwnerType")]
	pub default_case_owner_type: Option<String>,
	#[serde(rename = "defaultCaseUser")]
	pub default_case_user: Option<String>,
	#[serde(rename = "emailActionDefaultsHandlerClass")]
	pub email_action_defaults_handler_class: Option<String>,
	#[serde(rename = "emailToCase")]
	pub email_to_case: Option<EmailToCaseSettings>,
	#[serde(rename = "enableCaseFeed")]
	pub enable_case_feed: Option<bool>,
	#[serde(rename = "enableCaseSwarming")]
	pub enable_case_swarming: Option<bool>,
	#[serde(rename = "enableCollapseEmailThread")]
	pub enable_collapse_email_thread: Option<bool>,
	#[serde(rename = "enableDraftEmails")]
	pub enable_draft_emails: Option<bool>,
	#[serde(rename = "enableEarlyEscalationRuleTriggers")]
	pub enable_early_escalation_rule_triggers: Option<bool>,
	#[serde(rename = "enableEmailActionDefaultsHandler")]
	pub enable_email_action_defaults_handler: Option<bool>,
	#[serde(rename = "enableEmailContactOnCasePost")]
	pub enable_email_contact_on_case_post: Option<bool>,
	#[serde(rename = "enableEscalateQfiToCaseInternal")]
	pub enable_escalate_qfi_to_case_internal: Option<bool>,
	#[serde(rename = "enableEscalateQfiToCaseNetworks")]
	pub enable_escalate_qfi_to_case_networks: Option<bool>,
	#[serde(rename = "enableExtNetworksCaseFeedEnabled")]
	pub enable_ext_networks_case_feed_enabled: Option<bool>,
	#[serde(rename = "enableMultiLangSolnSrchCSS")]
	pub enable_multi_lang_soln_srch_css: Option<bool>,
	#[serde(rename = "enableMultiLangSolnSrchPKB")]
	pub enable_multi_lang_soln_srch_pkb: Option<bool>,
	#[serde(rename = "enableMultiLangSolution")]
	pub enable_multi_lang_solution: Option<bool>,
	#[serde(rename = "enableSolutionCategory")]
	pub enable_solution_category: Option<bool>,
	#[serde(rename = "enableSolutionInlineCategory")]
	pub enable_solution_inline_category: Option<bool>,
	#[serde(rename = "enableSolutionShortSummary")]
	pub enable_solution_short_summary: Option<bool>,
	#[serde(rename = "enableSuggestedArticlesApplication")]
	pub enable_suggested_articles_application: Option<bool>,
	#[serde(rename = "enableSuggestedArticlesCustomerPortal")]
	pub enable_suggested_articles_customer_portal: Option<bool>,
	#[serde(rename = "enableSuggestedArticlesPartnerPortal")]
	pub enable_suggested_articles_partner_portal: Option<bool>,
	#[serde(rename = "enableSuggestedSolutions")]
	pub enable_suggested_solutions: Option<bool>,
	#[serde(rename = "escalateCaseBefore")]
	pub escalate_case_before: Option<bool>,
	#[serde(rename = "genericMessageEnabled")]
	pub generic_message_enabled: Option<bool>,
	#[serde(rename = "keepCaseMergeRecords")]
	pub keep_case_merge_records: Option<bool>,
	#[serde(rename = "keepRecordTypeOnAssignmentRule")]
	pub keep_record_type_on_assignment_rule: Option<bool>,
	#[serde(rename = "notifyContactOnCaseComment")]
	pub notify_contact_on_case_comment: Option<bool>,
	#[serde(rename = "notifyDefaultCaseOwner")]
	pub notify_default_case_owner: Option<bool>,
	#[serde(rename = "notifyOwnerOnCaseComment")]
	pub notify_owner_on_case_comment: Option<bool>,
	#[serde(rename = "notifyOwnerOnCaseOwnerChange")]
	pub notify_owner_on_case_owner_change: Option<bool>,
	#[serde(rename = "predictiveSupportEnabled")]
	pub predictive_support_enabled: Option<bool>,
	#[serde(rename = "showEmailAttachmentsInCaseAttachmentsRL")]
	pub show_email_attachments_in_case_attachments_rl: Option<bool>,
	#[serde(rename = "showFewerCloseActions")]
	pub show_fewer_close_actions: Option<bool>,
	#[serde(rename = "systemUserEmail")]
	pub system_user_email: Option<String>,
	#[serde(rename = "useSystemEmailAddress")]
	pub use_system_email_address: Option<bool>,
	#[serde(rename = "useSystemUserAsDefaultCaseUser")]
	pub use_system_user_as_default_case_user: Option<bool>,
	#[serde(rename = "visibleInCssCheckbox")]
	pub visible_in_css_checkbox: Option<bool>,
	#[serde(rename = "webToCase")]
	pub web_to_case: Option<WebToCaseSettings>,
	#[serde(rename = "fullName")]
	pub full_name: Option<String>,
}
