use serde::{Deserialize};

#[derive(Debug, Deserialize)]
pub struct IndustriesSettings  {
	#[serde(rename = "allowMultipleProducersToWorkOnSamePolicy")]
	pub allow_multiple_producers_to_work_on_same_policy: Option<bool>,
	#[serde(rename = "appointmentDistributionOrgPref")]
	pub appointment_distribution_org_pref: Option<bool>,
	#[serde(rename = "captureResourceUtilizationOrgPref")]
	pub capture_resource_utilization_org_pref: Option<bool>,
	#[serde(rename = "createCustomerPropertyFromLAProperty")]
	pub create_customer_property_from_la_property: Option<bool>,
	#[serde(rename = "createFSCAssetFromLAAsset")]
	pub create_fsc_asset_from_la_asset: Option<bool>,
	#[serde(rename = "createFSCAssetFromLAProperty")]
	pub create_fsc_asset_from_la_property: Option<bool>,
	#[serde(rename = "createFSCLiabilityFromLAFinancial")]
	pub create_fsc_liability_from_la_financial: Option<bool>,
	#[serde(rename = "createFSCLiabilityFromLALiability")]
	pub create_fsc_liability_from_la_liability: Option<bool>,
	#[serde(rename = "createFinancialAccountFromLAAsset")]
	pub create_financial_account_from_la_asset: Option<bool>,
	#[serde(rename = "createFinancialAccountFromLALiability")]
	pub create_financial_account_from_la_liability: Option<bool>,
	#[serde(rename = "createFinancialAccountsFromLAFinancials")]
	pub create_financial_accounts_from_la_financials: Option<bool>,
	#[serde(rename = "createFinancialAccountsFromLAProperty")]
	pub create_financial_accounts_from_la_property: Option<bool>,
	#[serde(rename = "enableAIAccelerator")]
	pub enable_ai_accelerator: Option<bool>,
	#[serde(rename = "enableAWSTextractAnalyzeIDPref")]
	pub enable_aws_textract_analyze_id_pref: Option<bool>,
	#[serde(rename = "enableAccessToMasterListOfCoverageTypes")]
	pub enable_access_to_master_list_of_coverage_types: Option<bool>,
	#[serde(rename = "enableAccountScoreEnabled")]
	pub enable_account_score_enabled: Option<bool>,
	#[serde(rename = "enableActionableList")]
	pub enable_actionable_list: Option<bool>,
	#[serde(rename = "enableAnyResourceTypeOrgPref")]
	pub enable_any_resource_type_org_pref: Option<bool>,
	#[serde(rename = "enableAppFrmAnywhereOrgPref")]
	pub enable_app_frm_anywhere_org_pref: Option<bool>,
	#[serde(rename = "enableAppInviteOrgPref")]
	pub enable_app_invite_org_pref: Option<bool>,
	#[serde(rename = "enableBlockResourceAvailabilityOrgPref")]
	pub enable_block_resource_availability_org_pref: Option<bool>,
	#[serde(rename = "enableBusinessMessenger")]
	pub enable_business_messenger: Option<bool>,
	#[serde(rename = "enableCalculationUsingParentPolicyOnly")]
	pub enable_calculation_using_parent_policy_only: Option<bool>,
	#[serde(rename = "enableCallReportAdminContextPref")]
	pub enable_call_report_admin_context_pref: Option<bool>,
	#[serde(rename = "enableCareMgmtSlackAccess")]
	pub enable_care_mgmt_slack_access: Option<bool>,
	#[serde(rename = "enableChurnPredictionRT")]
	pub enable_churn_prediction_rt: Option<bool>,
	#[serde(rename = "enableClaimMgmt")]
	pub enable_claim_mgmt: Option<bool>,
	#[serde(rename = "enableClinicalDataModel")]
	pub enable_clinical_data_model: Option<bool>,
	#[serde(rename = "enableCompliantDataSharingForAccount")]
	pub enable_compliant_data_sharing_for_account: Option<bool>,
	#[serde(rename = "enableCompliantDataSharingForCustomObjects")]
	pub enable_compliant_data_sharing_for_custom_objects: Option<bool>,
	#[serde(rename = "enableCompliantDataSharingForFinancialDeal")]
	pub enable_compliant_data_sharing_for_financial_deal: Option<bool>,
	#[serde(rename = "enableCompliantDataSharingForInteraction")]
	pub enable_compliant_data_sharing_for_interaction: Option<bool>,
	#[serde(rename = "enableCompliantDataSharingForInteractionSummary")]
	pub enable_compliant_data_sharing_for_interaction_summary: Option<bool>,
	#[serde(rename = "enableCompliantDataSharingForOpportunity")]
	pub enable_compliant_data_sharing_for_opportunity: Option<bool>,
	#[serde(rename = "enableComprehendMedical")]
	pub enable_comprehend_medical: Option<bool>,
	#[serde(rename = "enableContactCenterAccess")]
	pub enable_contact_center_access: Option<bool>,
	#[serde(rename = "enableCreateMultiAttendeeEventOrgPref")]
	pub enable_create_multi_attendee_event_org_pref: Option<bool>,
	#[serde(rename = "enableCrisisCenterAccess")]
	pub enable_crisis_center_access: Option<bool>,
	#[serde(rename = "enableCustomFlowsOnCycleCount")]
	pub enable_custom_flows_on_cycle_count: Option<bool>,
	#[serde(rename = "enableCustomFlowsOnExpiryPage")]
	pub enable_custom_flows_on_expiry_page: Option<bool>,
	#[serde(rename = "enableDealManagement")]
	pub enable_deal_management: Option<bool>,
	#[serde(rename = "enableDisclsReprtFeatureOff")]
	pub enable_discls_reprt_feature_off: Option<bool>,
	#[serde(rename = "enableDiscoveryFrameworkMetadata")]
	pub enable_discovery_framework_metadata: Option<bool>,
	#[serde(rename = "enableDpeProviderSearchSettingsOrgPref")]
	pub enable_dpe_provider_search_settings_org_pref: Option<bool>,
	#[serde(rename = "enableEducationCloud")]
	pub enable_education_cloud: Option<bool>,
	#[serde(rename = "enableEinsteinDocReader")]
	pub enable_einstein_doc_reader: Option<bool>,
	#[serde(rename = "enableEinsteinVisits")]
	pub enable_einstein_visits: Option<bool>,
	#[serde(rename = "enableEnhancedQuestionCreation")]
	pub enable_enhanced_question_creation: Option<bool>,
	#[serde(rename = "enableEventManagementOrgPref")]
	pub enable_event_management_org_pref: Option<bool>,
	#[serde(rename = "enableEventWriteOrgPref")]
	pub enable_event_write_org_pref: Option<bool>,
	#[serde(rename = "enableExistingHealthCloudOrg")]
	pub enable_existing_health_cloud_org: Option<bool>,
	#[serde(rename = "enableFSCInsuranceReport")]
	pub enable_fsc_insurance_report: Option<bool>,
	#[serde(rename = "enableFinancialDealCallReportCmpPref")]
	pub enable_financial_deal_call_report_cmp_pref: Option<bool>,
	#[serde(rename = "enableFinancialDealCallReportPref")]
	pub enable_financial_deal_call_report_pref: Option<bool>,
	#[serde(rename = "enableFinancialDealRoleHierarchy")]
	pub enable_financial_deal_role_hierarchy: Option<bool>,
	#[serde(rename = "enableGnrcDisclsFrmwrk")]
	pub enable_gnrc_discls_frmwrk: Option<bool>,
	#[serde(rename = "enableHCReferralScoring")]
	pub enable_hc_referral_scoring: Option<bool>,
	#[serde(rename = "enableIESentimentAnalysis")]
	pub enable_ie_sentiment_analysis: Option<bool>,
	#[serde(rename = "enableIndustriesAssessment")]
	pub enable_industries_assessment: Option<bool>,
	#[serde(rename = "enableIndustriesAssessmentGuestOrgPref")]
	pub enable_industries_assessment_guest_org_pref: Option<bool>,
	#[serde(rename = "enableIndustriesKYC")]
	pub enable_industries_kyc: Option<bool>,
	#[serde(rename = "enableIndustriesRebates")]
	pub enable_industries_rebates: Option<bool>,
	#[serde(rename = "enableIntegratedCareManagementSetting")]
	pub enable_integrated_care_management_setting: Option<bool>,
	#[serde(rename = "enableInteractionCstmSharingPref")]
	pub enable_interaction_cstm_sharing_pref: Option<bool>,
	#[serde(rename = "enableInteractionRoleHierarchy")]
	pub enable_interaction_role_hierarchy: Option<bool>,
	#[serde(rename = "enableInteractionSummaryPref")]
	pub enable_interaction_summary_pref: Option<bool>,
	#[serde(rename = "enableInteractionSummaryRoleHierarchy")]
	pub enable_interaction_summary_role_hierarchy: Option<bool>,
	#[serde(rename = "enableManyToManyRelationships")]
	pub enable_many_to_many_relationships: Option<bool>,
	#[serde(rename = "enableMedRecSetting")]
	pub enable_med_rec_setting: Option<bool>,
	#[serde(rename = "enableMedicalDeviceEnabled")]
	pub enable_medical_device_enabled: Option<bool>,
	#[serde(rename = "enableMedicationManagementEnabled")]
	pub enable_medication_management_enabled: Option<bool>,
	#[serde(rename = "enableMortgageRlaTotalsOrgPref")]
	pub enable_mortgage_rla_totals_org_pref: Option<bool>,
	#[serde(rename = "enableMulesoftFhirR4Apis")]
	pub enable_mulesoft_fhir_r_4_apis: Option<bool>,
	#[serde(rename = "enableMultiResourceOrgPref")]
	pub enable_multi_resource_org_pref: Option<bool>,
	#[serde(rename = "enableMultipleCareProgramEnrolleeOrgPref")]
	pub enable_multiple_care_program_enrollee_org_pref: Option<bool>,
	#[serde(rename = "enableMultipleTopicsForShiftsOrgPref")]
	pub enable_multiple_topics_for_shifts_org_pref: Option<bool>,
	#[serde(rename = "enableObjectDetection")]
	pub enable_object_detection: Option<bool>,
	#[serde(rename = "enableOverbookingOrgPref")]
	pub enable_overbooking_org_pref: Option<bool>,
	#[serde(rename = "enablePatientAppointmentSchedulingOrgPref")]
	pub enable_patient_appointment_scheduling_org_pref: Option<bool>,
	#[serde(rename = "enablePatientServicesOrchestration")]
	pub enable_patient_services_orchestration: Option<bool>,
	#[serde(rename = "enablePolicyAdministration")]
	pub enable_policy_administration: Option<bool>,
	#[serde(rename = "enableProviderSearchSyncOrgPref")]
	pub enable_provider_search_sync_org_pref: Option<bool>,
	#[serde(rename = "enableRBLUsingCalcService")]
	pub enable_rbl_using_calc_service: Option<bool>,
	#[serde(rename = "enableRecordRollup")]
	pub enable_record_rollup: Option<bool>,
	#[serde(rename = "enableReferralScoring")]
	pub enable_referral_scoring: Option<bool>,
	#[serde(rename = "enableSCAssignFootprint")]
	pub enable_sc_assign_footprint: Option<bool>,
	#[serde(rename = "enableSCBEIEnabled")]
	pub enable_scbei_enabled: Option<bool>,
	#[serde(rename = "enableSCCarbonAccounting")]
	pub enable_sc_carbon_accounting: Option<bool>,
	#[serde(rename = "enableSCCarbonCreditAlloc")]
	pub enable_sc_carbon_credit_alloc: Option<bool>,
	#[serde(rename = "enableSCCreateFootprint")]
	pub enable_sc_create_footprint: Option<bool>,
	#[serde(rename = "enableSCDGF")]
	pub enable_scdgf: Option<bool>,
	#[serde(rename = "enableSCEmssnsForecasting")]
	pub enable_sc_emssns_forecasting: Option<bool>,
	#[serde(rename = "enableSCExpansionUseCase")]
	pub enable_sc_expansion_use_case: Option<bool>,
	#[serde(rename = "enableSCExternalEngMgmt")]
	pub enable_sc_external_eng_mgmt: Option<bool>,
	#[serde(rename = "enableSCGenrateCnsmpRcd")]
	pub enable_sc_genrate_cnsmp_rcd: Option<bool>,
	#[serde(rename = "enableSCSNGManagement")]
	pub enable_scsng_management: Option<bool>,
	#[serde(rename = "enableSCScope3HubEnabled")]
	pub enable_sc_scope_3_hub_enabled: Option<bool>,
	#[serde(rename = "enableSCSplitCnsmpRcd")]
	pub enable_sc_split_cnsmp_rcd: Option<bool>,
	#[serde(rename = "enableSCTargetSetting")]
	pub enable_sc_target_setting: Option<bool>,
	#[serde(rename = "enableSCWasteManagement")]
	pub enable_sc_waste_management: Option<bool>,
	#[serde(rename = "enableSCWaterManagement")]
	pub enable_sc_water_management: Option<bool>,
	#[serde(rename = "enableSentimentAnalysis")]
	pub enable_sentiment_analysis: Option<bool>,
	#[serde(rename = "enableShareSaWithArOrgPref")]
	pub enable_share_sa_with_ar_org_pref: Option<bool>,
	#[serde(rename = "enableSlackForCib")]
	pub enable_slack_for_cib: Option<bool>,
	#[serde(rename = "enableSmartTags")]
	pub enable_smart_tags: Option<bool>,
	#[serde(rename = "enableSustainabilityCloud")]
	pub enable_sustainability_cloud: Option<bool>,
	#[serde(rename = "enableSyncInteractionsPref")]
	pub enable_sync_interactions_pref: Option<bool>,
	#[serde(rename = "enableTearSheetPref")]
	pub enable_tear_sheet_pref: Option<bool>,
	#[serde(rename = "enableTextExtract")]
	pub enable_text_extract: Option<bool>,
	#[serde(rename = "enableTimelinePref")]
	pub enable_timeline_pref: Option<bool>,
	#[serde(rename = "enableTopicOrTemplate")]
	pub enable_topic_or_template: Option<bool>,
	#[serde(rename = "enableTopicTimeSlot")]
	pub enable_topic_time_slot: Option<bool>,
	#[serde(rename = "enableUMPayerAppAccessOrgPreference")]
	pub enable_um_payer_app_access_org_preference: Option<bool>,
	#[serde(rename = "enableVideoVisitsOrgPref")]
	pub enable_video_visits_org_pref: Option<bool>,
	#[serde(rename = "enableVisitCalendarSync")]
	pub enable_visit_calendar_sync: Option<bool>,
	#[serde(rename = "enableVisitInventoryEnabled")]
	pub enable_visit_inventory_enabled: Option<bool>,
	#[serde(rename = "loanApplicantAddressAutoCreation")]
	pub loan_applicant_address_auto_creation: Option<bool>,
	#[serde(rename = "loanApplicantAutoCreation")]
	pub loan_applicant_auto_creation: Option<bool>,
	#[serde(rename = "rlaEditIfAccHasEdit")]
	pub rla_edit_if_acc_has_edit: Option<bool>,
	#[serde(rename = "transformRBLtoDPE")]
	pub transform_rb_lto_dpe: Option<bool>,
}
