use crate::metadata::ObjectRelationship::ObjectRelationship;
use crate::metadata::ReportLayoutSection::ReportLayoutSection;
use crate::metadata::ReportTypeCategory::ReportTypeCategory;
use serde::{Deserialize};

#[derive(Debug, Deserialize)]
pub struct ReportType  {
	#[serde(rename = "autogenerated")]
	pub autogenerated: Option<bool>,
	#[serde(rename = "baseObject")]
	pub base_object: String,
	#[serde(rename = "category")]
	pub category: ReportTypeCategory,
	#[serde(rename = "deployed")]
	pub deployed: bool,
	#[serde(rename = "description")]
	pub description: Option<String>,
	#[serde(rename = "join")]
	pub join: Option<ObjectRelationship>,
	#[serde(rename = "label")]
	pub label: String,
	#[serde(rename = "sections")]
	pub sections: Option<Vec<ReportLayoutSection>>,
}
