use serde::{Deserialize};

#[derive(Debug, Deserialize)]
pub struct UserEngagementSettings  {
	#[serde(rename = "canGovCloudUseAdoptionApps")]
	pub can_gov_cloud_use_adoption_apps: Option<bool>,
	#[serde(rename = "doesScheduledSwitcherRunDaily")]
	pub does_scheduled_switcher_run_daily: Option<bool>,
	#[serde(rename = "enableCustomHelpGlobalSection")]
	pub enable_custom_help_global_section: Option<bool>,
	#[serde(rename = "enableHelpMenuShowFeedback")]
	pub enable_help_menu_show_feedback: Option<bool>,
	#[serde(rename = "enableHelpMenuShowHelp")]
	pub enable_help_menu_show_help: Option<bool>,
	#[serde(rename = "enableHelpMenuShowNewUser")]
	pub enable_help_menu_show_new_user: Option<bool>,
	#[serde(rename = "enableHelpMenuShowSearch")]
	pub enable_help_menu_show_search: Option<bool>,
	#[serde(rename = "enableHelpMenuShowSfdcContent")]
	pub enable_help_menu_show_sfdc_content: Option<bool>,
	#[serde(rename = "enableHelpMenuShowShortcut")]
	pub enable_help_menu_show_shortcut: Option<bool>,
	#[serde(rename = "enableHelpMenuShowSupport")]
	pub enable_help_menu_show_support: Option<bool>,
	#[serde(rename = "enableHelpMenuShowTrailhead")]
	pub enable_help_menu_show_trailhead: Option<bool>,
	#[serde(rename = "enableIBILOptOutDashboards")]
	pub enable_ibil_opt_out_dashboards: Option<bool>,
	#[serde(rename = "enableIBILOptOutEvents")]
	pub enable_ibil_opt_out_events: Option<bool>,
	#[serde(rename = "enableIBILOptOutReports")]
	pub enable_ibil_opt_out_reports: Option<bool>,
	#[serde(rename = "enableIBILOptOutTasks")]
	pub enable_ibil_opt_out_tasks: Option<bool>,
	#[serde(rename = "enableLexToClassicFeedbackEnable")]
	pub enable_lex_to_classic_feedback_enable: Option<bool>,
	#[serde(rename = "enableOrchestrationInSandbox")]
	pub enable_orchestration_in_sandbox: Option<bool>,
	#[serde(rename = "enableOrgUserAssistEnabled")]
	pub enable_org_user_assist_enabled: Option<bool>,
	#[serde(rename = "enableScheduledSwitcher")]
	pub enable_scheduled_switcher: Option<bool>,
	#[serde(rename = "enableSfdcProductFeedbackSurvey")]
	pub enable_sfdc_product_feedback_survey: Option<bool>,
	#[serde(rename = "enableShowSalesforceUserAssist")]
	pub enable_show_salesforce_user_assist: Option<bool>,
	#[serde(rename = "isAutoTransitionDelayed")]
	pub is_auto_transition_delayed: Option<bool>,
	#[serde(rename = "isCrucNotificationDisabled")]
	pub is_cruc_notification_disabled: Option<bool>,
	#[serde(rename = "isCustomProfileAutoTransitionDelayed")]
	pub is_custom_profile_auto_transition_delayed: Option<bool>,
	#[serde(rename = "isLEXWelcomeMatDisabled")]
	pub is_lex_welcome_mat_disabled: Option<bool>,
	#[serde(rename = "isMeetTheAssistantDisabledInClassic")]
	pub is_meet_the_assistant_disabled_in_classic: Option<bool>,
	#[serde(rename = "isMeetTheAssistantDisabledInLightning")]
	pub is_meet_the_assistant_disabled_in_lightning: Option<bool>,
	#[serde(rename = "isSmartNudgesDisabled")]
	pub is_smart_nudges_disabled: Option<bool>,
	#[serde(rename = "optimizerAppEnabled")]
	pub optimizer_app_enabled: Option<bool>,
	#[serde(rename = "fullName")]
	pub full_name: Option<String>,
}
